Saving image GID in the discount
tiki/tiki-shopify-web pull request #37
Opened 2023-09-21 18:48 UTC by MiroBenicio

# Issues Addressed
Closes https://github.com/tiki/apps-shopify-extensions/issues/43

## Additional Information
Now its saving the GID of the MediaImage into the discount data

2023-09-21 19:02 UTC, ricardobrg requested changes

2023-09-21 19:02 UTC, ricardolg-dev commented on src/_worker.ts
> +  .post(`${API.Consts.API_LATEST}/upload/stage`, Discount.stagedUpload)
since it is all done in the same call just use "upload"

2023-09-21 19:02 UTC, ricardolg-dev commented on src/components/BannerImageDescription.tsx
> +          console.log('teste componente', file)
remove logs

2023-09-21 19:02 UTC, ricardolg-dev commented on src/components/BannerImageDescription.tsx
> +      {/* <Thumbnail
remove comment and add story to put thumbnail

2023-09-21 19:02 UTC, ricardolg-dev commented on src/components/providers/AppBridgeProvider.tsx
> +  const apiKey = '1949a2edb1cab0db98cdf67e81742982'; // process.env.SHOPIFY_API_KEY
rollback. Create story to use env vars

2023-09-21 19:02 UTC, ricardolg-dev commented on src/pages/discount/order/Create.tsx
> +      'https://tiki-web.pages.dev/api/latest/discount',
rollback

2023-09-21 19:02 UTC, ricardobrg commented on src/pages/discount/order/Create.tsx
> +      'https://tiki-web.pages.dev/api/latest/discount',
check if it is possible to use request URL to build it.

2023-09-21 19:02 UTC, ricardobrg commented on src/pages/discount/product/Create.tsx
> +    await authenticatedFetch('https://tiki-web.pages.dev/api/latest/discount', {
rollback

2023-09-22 12:11 UTC, ricardobrg approved these changes

2023-09-22 12:11 UTC, merged